implemented task
mate-academy/jv-storage pull request #1086
Opened 2023-05-03 13:40 UTC by mpankrad

2023-05-03 14:13 UTC, MykytaKat requested changes
let`s improve your solution

2023-05-03 14:13 UTC, MykytaKat commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        for (int i = 0; i < size; i += 2) {
for (int i = 0; i < size; i++)

2023-05-03 14:13 UTC, MykytaKat commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (key == null && keysAndValues[i] == null) {
let`s make separate method to avoid code duplication in put and get methods and make code more readable

2023-05-03 15:37 UTC, MykytaKat requested changes
delete 'import Arrays' and if block in 42 line

2023-05-04 09:31 UTC, MykytaKat approved these changes
good job!

2023-05-05 08:56 UTC, rovein requested changes
Good job! But let's improve your solution ;)

2023-05-05 08:56 UTC, rovein commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private final int pairNum = 2;
```suggestion
    private static final int PAIR_NUM = 2;
```

2023-05-05 08:56 UTC, rovein commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private final int maxSize;
```suggestion
    private static final int MAX_SIZE;
```

2023-05-05 08:56 UTC, rovein commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        keysAndValues = new Object[20];
```suggestion
        keysAndValues = new Object[MAX_SIZE * PAIR_NUM];
```

2023-05-05 08:56 UTC, rovein commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    || key != null && key.equals(keysAndValues[i])) {
```suggestion
            if (keysAreEqual(key, keysAndValues[i]) {
```

2023-05-05 08:56 UTC, rovein commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    || key != null && key.equals(keysAndValues[i])) {
The same. Move to a separate method.

2023-05-05 08:56 UTC, rovein commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        // return number of elements divided by two
Let's remove the comment.

2023-05-09 08:48 UTC, sarakhmen approved these changes
Good job, let's not make the same mistakes next time ;)

2023-05-09 08:48 UTC, sarakhmen commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private boolean keysAreEqual(K key, Object storedKey) {
let's put your private methods after public ones

2025-08-08 06:59 UTC, closed without merging