StorageImplFunctions
mate-academy/jv-storage pull request #1150
Opened 2023-07-06 20:15 UTC by ConfusedSatlan

2023-07-10 11:31 UTC, DmytroV95 approved these changes

2023-07-10 14:11 UTC, nacenik requested changes
Good solution, let's improve it)

2023-07-10 14:11 UTC, nacenik commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    }
do you really need to increase capacity?? 
it should be maximum 10 elements 
<img width="825" alt="image" src="https://github.com/mate-academy/jv-storage/assets/32339836/956f7c07-7988-48df-b43a-18ed837a3639">

2023-07-10 14:11 UTC, nacenik commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                if (storageArray[i].getKey().equals(key)) {
maybe better to merge and put into separate method these two conditions to reuse them?

2023-07-10 14:11 UTC, nacenik commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            }
you can simplify here using only one if

2023-07-10 14:11 UTC, nacenik commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +
redundant line

2023-07-10 14:12 UTC, nacenik commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    public static final int DEFAULT_SIZE_PAIR = 10;
is it default size or max size?

2023-07-11 14:09 UTC, KseniiaMakarova requested changes

2023-07-11 14:09 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        if (size == storageArray.length) {
```suggestion
        if (size == MAX_SIZE_PAIR) {
```
just easier to read

2023-07-11 14:09 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            } else if (key == null && storageArray[i].getKey() == null) {
we don't need else after return

and also you don't need this check, because if they are both null - your `equals()` method will return true

2023-07-11 14:09 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private boolean equals(K key, K keySecond) {
```suggestion
    private boolean equals(K key, K secondKey) {
```

2023-07-11 14:09 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    public static final int MAX_SIZE_PAIR = 10;
```suggestion
    public static final int MAX_SIZE = 10;
```

2024-04-22 10:56 UTC, closed without merging