implemented put, get, size methods
mate-academy/jv-storage pull request #1173
Opened 2023-07-10 13:53 UTC by IvanFadieiev

2023-07-10 14:10 UTC, ivan0dyatlyukkk approved these changes
Great job!

2023-07-10 17:09 UTC, Zel1oy requested changes

2023-07-10 17:09 UTC, Zel1oy commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
You should add check when storage is full

2023-07-11 09:49 UTC, Zel1oy requested changes

2023-07-11 09:49 UTC, Zel1oy commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        if (size == 10) {
Don't use magic numbers in your code

2023-07-11 12:12 UTC, Zel1oy approved these changes
Approved

2023-07-11 13:49 UTC, nacenik requested changes
Good solution, let's improve it a little bit :)

2023-07-11 13:49 UTC, nacenik commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private V[] values;
make these fields final too

2023-07-11 13:50 UTC, KseniiaMakarova approved these changes

2023-07-11 13:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        size = 0;
```suggestion
```
int is 0 by default

2026-07-11 10:08 UTC, closed without merging