jv-storage-solution
mate-academy/jv-storage pull request #1185
Opened 2023-07-17 11:50 UTC by literandltx

2023-07-17 12:01 UTC, Rommelua requested changes

2023-07-17 12:01 UTC, Rommelua commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        storageValue = (V[]) new Object[0];
keep it simple - create arrays with length 10
![image](https://github.com/mate-academy/jv-storage/assets/20326858/ad931a08-91c4-4a68-85d0-8db406abc005)

2023-07-17 12:15 UTC, literandltx commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        storageValue = (V[]) new Object[0];
But it's better than having a fixed size, isn't it?
Also, the implementation will also be slightly different

2023-07-17 17:10 UTC, aaananas requested changes

2023-07-17 17:10 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        this.size = 0;
```suggestion
```

2023-07-17 17:10 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private static final int SIZE = 10;
```suggestion
    private static final int MAX_CAPACITY = 10;
```

2023-07-17 17:10 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
```suggestion
        for (int i = 0; i < size; i++) {
            if ((storageKey[i] != null && storageKey[i].equals(key))
                    || (storageKey[i] == null && key == null)) {
                    storageValue[i] = value;
                    return;
            }
        }
        storageKey[size] = key;
        storageValue[size] = value;

        size++;
```

2023-07-18 09:20 UTC, Rommelua commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        storageValue = (V[]) new Object[0];
see this) https://www.youtube.com/watch?v=Ot2eB07rjcI&t=508s

2023-07-18 09:21 UTC, Rommelua approved these changes

2023-07-18 09:21 UTC, Rommelua commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    || (storageKey[i] == null && key == null)) {
```suggestion
                    || storageKey[i] == key) {
```

2025-01-10 11:26 UTC, closed without merging