Realized StorageImpl with 2 arrays and ability to save null keys
mate-academy/jv-storage pull request #1262
Opened 2023-09-14 15:53 UTC by Trayvor

2023-09-14 17:49 UTC, kozhukhovsky requested changes

2023-09-14 17:49 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (key != null && keyArr[i] != null) {
You can combine the check so that there is only one if block
key == keys[i] || key != null && key.equals(keys[i])

2023-09-14 17:49 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private final K[] keyArr = (K[])new Object[ARRAY_SIZE];
```suggestion
    private final K[] keys = (K[])new Object[ARRAY_SIZE];
```

2023-09-14 17:49 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private final V[] valArr = (V[])new Object[ARRAY_SIZE];
```suggestion
    private final V[] values = (V[])new Object[ARRAY_SIZE];
```

2023-09-14 17:49 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private int pos = 0;
```suggestion
    private int size;
```

0 if default value for int

2023-09-14 17:49 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (keyArr[i] != null && key != null) {
same, combine check

2023-09-19 09:51 UTC, olekskov requested changes

2023-09-19 11:46 UTC, olekskov approved these changes
Good job

2024-11-10 17:53 UTC, closed without merging