realized StorageImpl class
mate-academy/jv-storage pull request #1285
Opened 2023-10-03 14:18 UTC by proxychang

2023-10-04 10:29 UTC, TarasYurkovskyi requested changes
Overall, good jod mate

2023-10-04 10:29 UTC, TarasYurkovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private Object[][] items = new Object[MAX_ITEMS_NUMBER][ITEM_FIELDS];
i would reccomend to intialize this in constructor, follow this rule https://mate-academy.github.io/jv-program-common-mistakes/java-core/generics/storage.html#all-non-constant-fields-should-be-initialized-in-the-constructor

2023-10-04 10:29 UTC, TarasYurkovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            }
i think u need to make 0 and 1 constants by following this rule https://mate-academy.github.io/jv-program-common-mistakes/java-core/generics/storage.html#any-magic-numbers-should-be-constants

2023-10-04 11:55 UTC, proxychang commented
> Overall, good jod mate

thanks, it was fixed!

2023-10-04 14:55 UTC, kshuryhin requested changes
Great job! Just some minor points to resolve

2023-10-04 14:55 UTC, kshuryhin commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        for (int i = 0; i < items.length; i++) {
I believe we can iterate up to `size` to avoid not needed iterations

2023-10-04 14:55 UTC, kshuryhin commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private Object[][] items;
Although that is really cool you've managed to solve the task in such way, it would be much more readable to use inner class to hold the key-value pairs.

2023-10-04 14:55 UTC, kshuryhin commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        size++;
What if the array is full? Consider to create some mechanism to deal with that case

2023-10-04 16:30 UTC, proxychang commented
> Great job! Just some minor points to resolve

done

2023-10-06 12:06 UTC, kshuryhin approved these changes
Great job!

2025-08-20 14:28 UTC, closed without merging