A generic class named StorageImpl is implemented, which implements th…
mate-academy/jv-storage pull request #1330
Opened 2023-10-31 19:19 UTC by rafik2211

Storage

A generic class named StorageImpl is implemented, which implements the Storage interface for key-value storage.
It defines a maximum size (MAX_SIZE) for the storage, which is set to 10. It uses two arrays, 'keys' and 'values', to store key-value pairs, both initially created with a size of MAX_SIZE. The 'size' variable keeps track of the number of elements currently in the storage. The put(K key, V value) method allows adding key-value pairs to the storage. It first checks if the key is null and, if so, searches for a null key in the storage. If the key is not null, it looks for an existing key in the storage. If the key is found, the method updates the associated value. If the key is not found, and the storage has room (size < MAX_SIZE), a new key-value pair is added to the arrays. The get(K key) method retrieves a value from the storage based on the provided key. It checks if the key is null and, if so, searches for a null key. If the key is not null, it searches for the key in the storage and returns the associated value. If the key is not found, it returns null. The size() method returns the current size of the storage, indicating how many key-value pairs are stored.

2023-11-01 12:20 UTC, kozhukhovsky requested changes

2023-11-01 12:20 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Storage.java
> +
```suggestion
```

2023-11-01 12:20 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private int size = 0;
```suggestion
    private int size;
```

0 is default value for int

2023-11-01 12:20 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                if (keys[i] == null) {
You can combine these two checks into one

2023-11-01 12:20 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                if (keys[i] == null) {
key == keys[i] || key != null && key.equals(keys[i])

2023-11-01 12:20 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            size++;
This is better to do anyway. But it turns out that the method worked without errors, but the result did not change.
It is necessary that if it is already greater than the maximum value, throw some kind of error.

2023-11-01 12:20 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                if (keys[i] == null) {
same, combine

2023-11-01 15:47 UTC, Ivan95kos requested changes
please, fix the previous comments

2023-11-01 15:47 UTC, Ivan95kos commented on src/main/java/core/basesyntax/Storage.java
> +
not fixed

2023-11-01 15:47 UTC, Ivan95kos commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private Object[] values = new Object[MAX_SIZE];
Use the parameterized types
All non-constant fields should be initialized in the constructor
```suggestion
    private K [] keys;
    private V [] values;
```

2023-11-01 15:47 UTC, Ivan95kos commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            size++;
not fixed

2023-11-03 10:19 UTC, kozhukhovsky approved these changes

2024-05-31 20:26 UTC, closed without merging