Resolved jv-storage Task
mate-academy/jv-storage pull request #1411
Opened 2024-02-12 15:53 UTC by DmitryLazyuka

2024-02-12 18:38 UTC, olekskov requested changes

2024-02-12 18:38 UTC, olekskov commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        this.values = (V[]) new Object[10];
Please move magic number to constant with proper naming

2024-02-12 18:38 UTC, olekskov commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
Usage of Objects class methods is prohibited in this task
https://github.com/mate-academy/jv-storage/blob/master/checklist.md#dont-use-class-objects

2024-02-12 18:38 UTC, olekskov commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
same here

2024-02-12 18:38 UTC, olekskov commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
And we should deal with null key same as any other. For us it doesn't matter
```suggestion
        for (int i = 0; i < keys.length; i++) {
            if (key == keys[i] || key != null && key.equals(keys[i])) {
                return values[i];
            }
        }    
```
Please use similar approach in put method

2024-02-13 11:23 UTC, Vasul-Pankiv requested changes

2024-02-13 11:23 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (values[i] == null) {
what if you want to put couple diff keys with null value?

2024-02-13 12:30 UTC, kozhukhovsky approved these changes

2026-06-04 07:56 UTC, closed without merging