solution
mate-academy/jv-storage pull request #1505
Opened 2024-05-23 12:21 UTC by mgsorigo

2024-05-23 15:06 UTC, MateuszRostek requested changes
Good job, but you didn't follow the rule to not use `Objects` class.

https://github.com/mate-academy/jv-storage/blob/master/checklist.md

2024-05-23 15:06 UTC, MateuszRostek commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (Objects.equals(keys[i], key)) {
![image](https://github.com/mate-academy/jv-storage/assets/140905715/4a95a879-694d-4b10-8cdb-7a85993aa41c)

2024-05-23 15:06 UTC, MateuszRostek commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (Objects.equals(keys[i], key)) {
![image](https://github.com/mate-academy/jv-storage/assets/140905715/26ca64e3-6259-4d15-9861-30a35a0584ee)

2024-05-24 06:06 UTC, mgsorigo commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (Objects.equals(keys[i], key)) {
the idea suggests such a solution.
![image](https://github.com/mate-academy/jv-storage/assets/95102618/622eeed8-88bb-4942-8276-67395518d154)

2024-05-24 07:46 UTC, MateuszRostek commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (Objects.equals(keys[i], key)) {
I know and you should use it later in your code, because it better approach overall, just for this task you should create it manually:)

2024-05-24 07:50 UTC, MateuszRostek approved these changes
Good job!

2024-05-24 07:50 UTC, MateuszRostek commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (Objects.equals(keys[i], key)) {
You should change it here as well:)

2024-05-24 07:51 UTC, MateuszRostek approved these changes
!

2024-08-12 10:07 UTC, closed without merging