Implemented a key-value store parameterized by two data types.
mate-academy/jv-storage pull request #1514
Opened 2024-06-13 18:56 UTC by Jacalius

2024-06-13 18:56 UTC, mateacademy-ai-mentor approved these changes

2024-06-13 18:56 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
>  public class StorageImpl<K, V> implements Storage<K, V> {
The class implementation should not begin with an empty line. Please remove the empty line before the class declaration.

2024-06-13 18:56 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    public StorageImpl() {
The constructor should not begin with an empty line. Please remove the redundant empty line.

2024-06-13 18:56 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
>      @Override
The method implementation for 'put' should not begin with an empty line. Please remove the redundant empty line.

2024-06-13 18:56 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
>      @Override
The method implementation for 'get' should not begin with an empty line. Please remove the redundant empty line.

2024-06-13 18:56 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
>      @Override
The method implementation for 'size' should not begin with an empty line. Please remove the redundant empty line.

2024-06-13 18:56 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    || keys[i] != null && keys[i].equals(key)) {
The comparison logic for keys is repeated in both the 'put' and 'get' methods. Consider moving this logic into a private method to avoid repetition and adhere to the DRY principle.

2024-06-13 18:56 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private K[] keys;
According to the checklist, you should not use class Objects. Instead, consider using a simple array or other data structures with primitive or custom object types if necessary.

2024-06-13 20:15 UTC, sarakhmen requested changes
let's slightly improve your solution :)

2024-06-13 20:15 UTC, sarakhmen commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        size = 0;
size is 0 by default

2024-06-14 05:43 UTC, Elena-Bruyako requested changes

2024-06-14 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        for (int i = 0; i < size; i++) {
To avoid duplication let's create separate method

```
private int indexOf(K key) {
        for (int i = 0; i < size; i++) {
            if (key == keys[i] || key != null && key.equals(keys[i])) {
                return i;
            }
        }
        return -1;
    }
```

2024-06-14 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        for (int i = 0; i < size; i++) {
```suggestion
        int index = indexOf(key);
        return index == -1 ? null : values[index];
```

2024-06-14 20:19 UTC, sarakhmen approved these changes
good job!

2024-10-21 15:45 UTC, closed without merging