create class StoregeImpl that can put and get date from the array by …
mate-academy/jv-storage pull request #1521
Opened 2024-06-22 12:34 UTC by ArtemHurievskyi

…the key
easy task for 3 days, nice job Artem, nice job

2024-06-24 10:54 UTC, sarakhmen requested changes
Let's improve your solution :)

2024-06-24 10:54 UTC, sarakhmen commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private static final int ARRAY_LENGTH = 5;
```suggestion
    private static final int ARRAY_LENGTH = 10;
```
please follow task description

2024-06-24 10:54 UTC, sarakhmen commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private V[] valueArray;
```suggestion
    private K[] keys;
    private V[] values;
```
let's not use such a general names as array/list/queue/map etc in our namings

2024-06-24 10:54 UTC, sarakhmen commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                return;
why did you need this null check here and separate logic for this case? what if the second element is null but 3-rd one isn't? the size will be incremented and the logic is weird

2024-06-24 10:54 UTC, sarakhmen commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
I'd recommend implementing additional private method getIndex/indexOf (whatever you want to name it) which will return the index of the provided key (or -1 in case key is absent in the keys array)

2024-06-28 13:28 UTC, Elena-Bruyako requested changes

2024-06-28 13:28 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
>      public void put(K key, V value) {
```suggestion
    public void put(K key, V value) {
        if (size == ARRAY_LENGTH) {
                throw new ArrayIndexOutOfBoundsException("Storage is full");
            }
```

You should check first

2024-06-28 13:28 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (key == keys[i] || (key != null && key.equals(keys[i]))) {
```suggestion
            if (key == keys[i] || key != null && key.equals(keys[i])) {
```

2024-06-28 20:15 UTC, sarakhmen approved these changes
lgtm!

2024-12-02 17:57 UTC, closed without merging