Solution-for-jv-storage
mate-academy/jv-storage pull request #1554
Opened 2024-08-01 10:59 UTC by aovozniuk1

2024-08-01 10:59 UTC, mateacademy-ai-mentor approved these changes
Great job on your Pull Request! While there are some minor issues like redundant null checks and a little repetition, these don't hinder the functionality of your code. 😊 Remember, using 'equals' for object comparison is a best practice and try to keep your code DRY by avoiding repeated logic. Keep it up! 👍

2024-08-01 10:59 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/Entity.java
> +public class Entity<K, V> {
The class `Entity` seems to be implemented correctly according to the checklist. However, ensure that the class name `Entity` is descriptive enough for its intended use within the project context.

2024-08-01 10:59 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/Entity.java
> +        return "StorageImpl{" +
The `toString` method references `StorageImpl` instead of `Entity`. This seems like a copy-paste error. Please correct the class name in the `toString` method to reflect the actual class name which is `Entity`.

2024-08-01 10:59 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private Entity<K, V> entity;
This field 'entity' is not used outside of the 'put' method. Consider declaring it as a local variable within the 'put' method to avoid unnecessary scope.

2024-08-01 10:59 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        if (!checkIfKeyPresent(key)) {
The 'checkIfKeyPresent' method is being called inside 'put', but its logic is repeated inside the 'else' block starting from line 22. This is not following the DRY principle. Consider refactoring to avoid code repetition.

2024-08-01 10:59 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                if (entityArr[i].getKey() == null || entityArr[i].getKey().equals(key)) {
Using '==' to compare keys could lead to incorrect behavior when keys are non-primitive data types. Use 'equals' method for object comparison to ensure correct key matching.

2024-08-01 10:59 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (entityArr[i].getKey() == key || entityArr[i].getKey().equals(key)) {
As mentioned before, use 'equals' instead of '==' for comparing object keys to ensure correct behavior, especially when keys are non-primitive data types.

2024-08-01 10:59 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (entityArr[i].getKey() == null && key != null) {
The check 'entityArr[i].getKey() == null && key != null' is redundant because 'equals' handles null checks internally. You can simplify this by removing the null check here.

2024-08-01 10:59 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (entityArr[i].getKey() == null && key != null) {
Similar to the comment on line 35, the null check here is redundant and can be removed for simplification.

2024-08-02 15:28 UTC, MAMentorFX requested changes

2024-08-02 15:28 UTC, MAMentorFX commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    public boolean checkIfKeyPresent(K key) {
```suggestion
    public boolean isKeyPresent(K key) {
```

2024-08-02 15:28 UTC, MAMentorFX commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            }
it can be simplified. just do the opposite check in the next if block

2024-08-02 15:28 UTC, MAMentorFX commented on src/main/java/core/basesyntax/impl/StorageImpl.java
>      public void put(K key, V value) {
please handle the `Storage is full` case

2024-08-02 15:28 UTC, MAMentorFX commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
I am pretty sure this can be simplified, without checkIfKeyPresent method. Just one for-loop with one if block inside

2024-08-05 07:04 UTC, aovozniuk1 commented on src/main/java/core/basesyntax/impl/StorageImpl.java
>      public void put(K key, V value) {
What does you mean?

2024-08-05 14:29 UTC, Elena-Bruyako requested changes

2024-08-05 14:29 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageFullException.java
> +public class StorageFullException extends RuntimeException {
rename

2024-08-05 14:29 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/EntityOfStorageImpl.java
> +public class EntityOfStorageImpl<K, V> {
rename

2024-08-05 14:29 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +
remove redundant blank lines

2024-08-06 08:48 UTC, aovozniuk1 commented on src/main/java/core/basesyntax/impl/EntityOfStorageImpl.java
> +public class EntityOfStorageImpl<K, V> {
Could you please give me your option? I renamed it Entity, I don't know the better option.

2024-08-06 09:55 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/EntityOfStorageImpl.java
> +public class EntityOfStorageImpl<K, V> {
Maybe Node?

2024-08-06 09:59 UTC, Elena-Bruyako requested changes

2024-08-06 09:59 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    && entityOfStorageArr[i].getKey().equals(key))) {
```suggestion
            if (entityOfStorageArr[i].getKey() == key || entityOfStorageArr[i].getKey() != null
                    && entityOfStorageArr[i].getKey().equals(key)) {
```

2024-08-06 09:59 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private Entity<K, V>[] entityOfStorageArr;
```suggestion
    private Entity<K, V>[] table;
```

2024-08-06 15:13 UTC, okuzan requested changes

2024-08-06 15:13 UTC, okuzan commented on src/main/java/core/basesyntax/Storage.java
> +    void put(K key, V value) throws FullStorageException;
let's not change the method signature. Moreover, it's Runtime (unchecked) exception

2024-08-06 15:13 UTC, okuzan commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    && table[i].getKey().equals(key)) {
this piece of code is common to both get and put, extract it to a separate private method and call it in two places

2024-08-07 10:07 UTC, MentorMateAcademy approved these changes

2025-07-30 09:18 UTC, closed without merging