corected method
mate-academy/jv-storage pull request #1568
Opened 2024-08-17 09:08 UTC by layzimayner

2024-08-17 09:08 UTC, mateacademy-ai-mentor requested changes
Hey there! It looks like there are a few key adjustments needed before we can move forward. We're not using certain collections like Maps or Lists just yet, so let's swap those out with arrays and tweak the logic to match. Once that's done, we'll be all set! Keep up the good work, and I'm excited to see the changes! 😊👍

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-08-17 09:08 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +import java.util.Map;
Don't use any kind of List, Set or Map. We will soon learn how these collections work. Instead, you should use an array or another way to store the elements.

2024-08-17 09:08 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private Map<K, V> storage;
Since we are not using Map, this field should be removed and replaced with an alternative storage solution, like an array, along with the necessary logic to handle storage operations.

2024-08-17 09:08 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
>  public class StorageImpl<K, V> implements Storage<K, V> {
Don't begin class or method implementation with an empty line. Please remove the empty line at the beginning of the class declaration.

2024-08-20 06:38 UTC, Elena-Bruyako requested changes

2024-08-20 06:38 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private Map<K, V> storage;
[Don't use any kind of List, Set or Map](https://github.com/mate-academy/jv-storage/blob/master/checklist.md#dont-use-any-kind-of-list-set-or-map)

2024-08-22 13:08 UTC, Elena-Bruyako requested changes

2024-08-22 13:08 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        size = 0;
```suggestion
```

2024-08-22 13:08 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private void resize() {
remove

2024-08-22 13:08 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (keys[i] == key || (keys[i] != null && keys[i].equals(key))) {
duplication of code, create separate indexOf method

2024-08-23 14:08 UTC, okuzan approved these changes

2024-08-23 14:08 UTC, okuzan commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                keys = newKeys;
nice, but resize is out of scope of the task anyway

2024-09-13 11:57 UTC, closed without merging