fixed impl
mate-academy/jv-storage pull request #1638
Opened 2024-11-13 11:50 UTC by LizaBalshv

2024-11-13 11:51 UTC, mateacademy-ai-mentor requested changes
****

Thank you for your hard work on implementing the `StorageImpl` class! Your solution meets many of the task requirements, such as implementing key-value storage and adhering to constraints like not using `List`, `Set`, or `Map`. However, there are a few critical issues that need to be addressed before we can approve the pull request:

1. **Object Comparison**: The use of `==` for comparing objects can lead to incorrect equality checks. Please replace it with the `equals()` method to ensure proper comparison of non-primitive types.

2. **Generic Arrays**: The use of generic arrays in Java is problematic due to type erasure, which can lead to runtime exceptions like `ClassCastException`. Consider using a different data structure that doesn't require casting, such as `ArrayList`, to avoid these issues.

These changes are crucial to ensure the robustness and correctness of your implementation. Once these issues are resolved, your code will be in great shape! Keep up the great work, and don't hesitate to reach out if you have any questions or need further assistance. 😊

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

🔄 Fix the issues, commit the changes, and then re-request my review using the `Re-request review` button in the Reviewers tab.

2024-11-13 11:51 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private final V[] values;
Using generic arrays like `K[] keys` and `V[] values` is not safe in Java due to type erasure. This can lead to `ClassCastException` at runtime. Consider using `List<K>` and `List<V>` or another collection type that doesn't rely on arrays.

2024-11-13 11:51 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        values = (V[]) new Object[MAXIMUM_CAPACITY];
Casting `new Object[MAXIMUM_CAPACITY]` to `(K[])` and `(V[])` is unsafe and can cause runtime exceptions. Consider using a different data structure that doesn't require casting, such as `ArrayList`.

2024-11-13 11:51 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    && keys[i].equals(key))) {
Using `==` for object comparison is not reliable for non-primitive types. Use `equals()` method to compare objects for equality.

2024-11-13 11:51 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    || (keys[i] != null && keys[i].equals(key))) {
Ensure that `equals()` is used for object comparison instead of `==` to avoid incorrect equality checks for non-primitive types.

2024-11-13 11:59 UTC, mateacademy-ai-mentor approved these changes
### Review Summary

Great job on implementing the `StorageImpl` class! 🎉 Your solution meets several key requirements, such as creating a key-value storage system and adhering to the constraint of using arrays with a maximum capacity of 10 elements. However, there are a few critical issues that need to be addressed to ensure the robustness and correctness of your code:

1. **Object Comparison**: Currently, the code uses `==` for comparing objects in the `put` method. It's important to replace this with the `equals()` method to ensure proper comparison of non-primitive types. This change is crucial for the correct functionality of your storage system.

2. **Generic Arrays**: The use of `Object[]` for storing keys and values can lead to runtime exceptions due to type erasure. Although the task constraints prohibit using `List`, `Set`, or `Map`, consider alternative approaches to ensure type safety and avoid potential `ClassCastException`.

Despite these issues, your implementation does not violate the checklist constraints, such as avoiding `List`, `Set`, or `Map`, and it uses informative variable names. All non-constant fields are correctly initialized in the constructor.

The decision to approve this pull request is made to help you move forward with your learning journey. Please review the comments to improve your code. Addressing these critical issues will enhance your understanding and prevent similar problems in the future. Keep up the good work and continue learning from your experiences! 🚀

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-11-13 11:59 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    && keys[i].equals(key))) {
Using `==` for object comparison can lead to incorrect equality checks. Replace `key == keys[i]` with `key.equals(keys[i])` to ensure proper comparison of non-primitive types.

2024-11-13 11:59 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                return (V) values[i];
Casting with `(V)` can lead to `ClassCastException` due to type erasure in generic arrays. Consider using a different data structure like `ArrayList` to avoid this issue.

2024-11-13 13:34 UTC, okuzan requested changes

2024-11-13 13:34 UTC, okuzan commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private final Object[] values;
use your K, V class type parameter, that's why we have them in the first place - to avoid using object

2024-11-13 13:34 UTC, okuzan commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private int size = 0;
0 is default value for int

2024-11-13 13:34 UTC, okuzan commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    || (keys[i] != null && keys[i].equals(key))) {
extract repeated logic from put and get into a private method that searches for a match and returns its index and -1 otherwise

2024-11-15 08:32 UTC, liliia-ponomarenko approved these changes
Awesome 😎

2024-11-15 08:32 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    || (keys[i] != null && keys[i].equals(key))) {
```suggestion
            if (keys[i] == null && key == null
                    || keys[i] != null && keys[i].equals(key)) {
```
redundant brackets

2026-06-09 13:15 UTC, closed without merging