completed Solution
mate-academy/jv-storage pull request #322
Opened 2021-07-27 15:23 UTC by dmitriy-tverdokhlibov

2021-07-28 07:02 UTC, RomanDubovskyi requested changes

2021-07-28 07:02 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            for (Pair pair : data) {
дуже багато for та if конструкцій, тобі достатньо тут ітерувати не весь масив а тільки до size() + можна зробити перевірку в одному іфі яка працюватиме і якщо якесь значення null i not null. Це спростить код в методі get()

2021-07-28 07:02 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        for (int i = 0; i < data.length; i++) {
аналогічно тут - ітеруємо до size якщо дійшли до кінця і не знайшли пару з таким самим ключем додаємо в кінець нову пару, якщо знайшли - замінюємо значення на нове

2021-08-03 06:56 UTC, RomanDubovskyi requested changes

2021-08-03 06:56 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            }
```suggestion
        for (int i = 0; i < size; i++) {
            if ((data[i].key == key || key != null && key.equals(data[i].key) {
                return (V) data[i].getValue();
            }
```

2021-08-03 06:56 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        if (size == 0) {
цей if зайвий: спочатку ітеруй свій масив до size якщо є однакові ключі тоді просто заміни value і вийди з методоу. Якщо пройшовся до size і не знайшов однаково ключа створи новий pair і додай в кінець масиву + інкремент сайзу

2021-08-05 06:26 UTC, RomanDubovskyi approved these changes

2021-08-05 06:26 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    && (data[j].getKey() == null && key == null)) {
```suggestion
            if (data[j].getKey() != null && data[j].getKey().equals(key)
                    || data[j].getKey() == key) {
```
в тебе не може бути dara[j] == null якщо ти ітеруєшся тільки до сайзу

2021-08-05 15:30 UTC, dmitriy-tverdokhlibov commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                    && (data[j].getKey() == null && key == null)) {
Исправлю. Спасибо за ревью!)

2025-04-23 19:03 UTC, closed without merging