put new key-value pair and to get value by key
mate-academy/jv-storage pull request #381
Opened 2021-10-02 16:38 UTC by inbox-reva

Hi! Please check my work.

2021-10-04 08:59 UTC, RomanDubovskyi requested changes

2021-10-04 08:59 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        for (Object[] ob : storage) {
для того щоб не проходитись по всіх елементах кожного разу краще збільшувати значення змінної `size` кожного разу, коли додається новий елемент

2021-10-04 08:59 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (key == null && storage[i][0] == null || key != null && key.equals(storage[i][0])) {
```suggestion
            if (key == storage[i][0] || key != null && key.equals(storage[i][0])) {
```

2021-10-04 08:59 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        for (int i = 0; i < storage.length; i++) {
тут можна проходитись не по всьому списку а тільки до size

2021-10-04 08:59 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (key == null && storage[i][0] == null || key != null && key.equals(storage[i][0])
давай тут аналогічно спростимо перевіркук

2021-10-05 06:32 UTC, RomanDubovskyi requested changes
поправ перевірки, решта гуд 👍

2021-10-05 06:32 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +                storage[i][0] = key;
ключ однаковий його вона не чіпати

2021-10-05 06:32 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (key == null && storage[i][0] == null || key != null && key.equals(storage[i][0])) {
> 

цей комент не виправелний

2021-10-05 18:00 UTC, inbox-reva commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (key == null && storage[i][0] == null || key != null && key.equals(storage[i][0])) {
спочатку пробува виправити ,але чомусь не працьовало, тому залишив. Сьогодні спробував знову і все вийшло. Дякую

2021-10-06 09:07 UTC, RomanDubovskyi approved these changes

2021-10-06 20:21 UTC, closed without merging