hw-jv-storage
mate-academy/jv-storage pull request #940
Opened 2023-02-04 21:22 UTC by ihor-sydorenko

2023-02-05 10:56 UTC, aaananas requested changes

2023-02-05 10:56 UTC, aaananas commented on src/test/java/core/basesyntax/StorageImplTest.java
>      @Test
dont change Test file, return the previous version

2023-02-06 10:46 UTC, Rommelua approved these changes

2023-02-06 10:46 UTC, Rommelua commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private int arraySize;
```suggestion
    private int size;
```

2024-09-03 05:47 UTC, closed without merging