implemented StotageImpl class
mate-academy/jv-storage pull request #958
Opened 2023-02-15 19:39 UTC by outref

2023-02-16 12:20 UTC, VitaliiPotseluiko commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            if (keys[i] == null && obj == null) {
first of all. it wil be better) And then You shoud join line 43 and 46. Think what kind of operator you have to use)
```suggestion
            if (obj == keys[i]) {
```

2023-02-16 12:24 UTC, VitaliiPotseluiko commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private int size = 0;
There is no necessary to initialize this field. Because default value is 0 as well.

2023-02-16 12:25 UTC, NazarZva requested changes

2023-02-16 12:25 UTC, NazarZva commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private K[] keys = (K[]) new Object[STARTING_CAPACITY];
```suggestion
    private K[] keys;
```
we need do this in constuctor

2023-02-16 12:25 UTC, NazarZva commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private V[] values = (V[]) new Object[STARTING_CAPACITY];
```suggestion
    private V[] values;
```
the same

2023-02-16 12:25 UTC, NazarZva commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
```suggestion
        if (keys.length == size) {
            increaseCapacity();
        }
```
we shouldn`t have this condition

2023-02-16 12:25 UTC, NazarZva commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    }
```suggestion
    //doubles arrays length
    private void increaseCapacity() {
        K[] newKeysArray = (K[]) new Object[keys.length * 2];
        System.arraycopy(keys, 0, newKeysArray, 0, keys.length);
        keys = newKeysArray;

        V[] newValuesArray = (V[]) new Object[values.length * 2];
        System.arraycopy(values, 0, newValuesArray, 0, values.length);
        values = newValuesArray;
    }
```
we shouldn`t use this method, bacause we assume that the maximum number of elements in our Storage is 10

2023-02-16 12:25 UTC, NazarZva commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            }
```suggestion
            if (keys[i] == obj || keys[i] != null && keys[i].equals(obj)) {
                return i;
            }
```
it will be better

2023-02-16 12:26 UTC, VitaliiPotseluiko commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private K[] keys = (K[]) new Object[STARTING_CAPACITY];
I my opinion fields keys and values you should initialize in constructor. Just my recommendation)

2023-02-16 13:09 UTC, outref commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    }
Added it just in case. I think it doesnt't hurt to have it)

2023-02-16 13:09 UTC, outref commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +            }
Added this and all other changes. Approve if you agree.

2023-02-16 13:09 UTC, outref commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private K[] keys = (K[]) new Object[STARTING_CAPACITY];
Added this and all other changes. Approve if you agree.

2023-02-16 14:25 UTC, VitaliiPotseluiko approved these changes

2023-02-16 15:57 UTC, NazarZva approved these changes

2023-02-17 08:51 UTC, maxline requested changes
Good job! Let's improve the solution

2023-02-17 08:51 UTC, maxline commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        if (keyIndex == -1) {
-1 is magic number.  
Also you can think about creating a boolean method that check if values already present in array. And call the new method in all places that check if `keyIndex == -1`

2023-02-17 08:51 UTC, maxline commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    //returns -1 if no such key was found
please remove comments from the code

2023-02-17 08:51 UTC, maxline commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    //doubles arrays length
please remove too

2023-02-17 09:48 UTC, maxline requested changes
one occurence with magic value missed

2023-02-17 09:48 UTC, maxline commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        if (keyIndex == -1) {
not fixed `-1` magic numbers

2023-02-17 10:30 UTC, nacenik requested changes
Just delete the useless blocks of code, and the task will be approved 😉

2023-02-17 10:30 UTC, nacenik commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        values = newValuesArray;
According to the task, the max size of the storage is 10 elements. Delete this method
![image](https://user-images.githubusercontent.com/32339836/219617892-4846e64f-cfe0-4fe4-8da7-7ed08cf27c15.png)

2023-02-17 10:30 UTC, nacenik commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
This condition is useless

2023-02-20 08:01 UTC, maxline approved these changes
Good job! Approved.

2025-08-25 04:06 UTC, closed without merging