Implemented methods
mate-academy/jv-storage pull request #967
Opened 2023-02-17 10:14 UTC by ValeriyM250

"put", "get", "size"

2023-02-17 11:30 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-02-17 11:30 UTC, Rommelua commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private Object [][] storage = new Object[2][10];
https://mate-academy.github.io/jv-program-common-mistakes/java-core/generics/storage.html

2023-02-17 15:55 UTC, andriy-shulepa requested changes

2023-02-17 15:55 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private Object [][] storage;
```suggestion
    private K[] keys;
    private V[] values;
```

With such approach your solution would be easier to read

2023-02-17 15:55 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
simplify to following approach
1. find index of key
2. set value by index and return
3. set key and value to storage capacity index (you may need to save capacity in class variable)

2023-02-22 19:42 UTC, aaananas requested changes

2023-02-22 19:42 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private static int sizeIndex;
```suggestion
    private int size;
```

2023-02-22 19:42 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        sizeIndex = START_INDEX_LENGTH;
```suggestion
```

2023-02-22 19:42 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
call findKeyIndex only once

2023-02-22 19:42 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        return (findKey(key) == -1) ? null : values[findKey(key)];
call findKeyIndex only once

2023-02-22 19:42 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        return keyIndex;
```suggestion
    private int findKeyIndez(K key) {
        for (int i = 0; i < keys.length; i++) {
            if (key == keys[i] || keys[i] != null && keys[i].equals(key)) {
                return i;
            }
        }
        return -1;
```

2023-02-22 19:42 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
```suggestion
        return size;
```

2023-02-23 18:56 UTC, aaananas requested changes

2023-02-23 18:56 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        size = -1;
```suggestion
```

2023-02-23 18:56 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +    private int keyIndex;
```suggestion
```

2023-02-23 18:56 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        }
```suggestion
        int keyIndex = findKey(key);
        if (keyIndex == -1) {
            keys[size] = key;
            values[size] = value;
            size++;
        } else {
            values[keyIndex] = value;
        }
```

2023-02-23 18:56 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        return size;
```suggestion
        return size;
```

2023-02-23 18:56 UTC, aaananas commented on src/main/java/core/basesyntax/impl/StorageImpl.java
> +        for (int i = 0; i < keys.length; i++) {
```suggestion
        for (int i = 0; i < size; i++) {
```

2023-02-24 10:58 UTC, Rommelua approved these changes

2024-09-03 05:53 UTC, closed without merging